apiVersion: v1
kind: Pod
metadata:
  name: safe-pod
  namespace: psa-test
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: nginx
    image: nginx
    securityContext:
      privileged: false 
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]